/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/js_plane.glb --types 
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    mat_3220964: THREE.MeshStandardMaterial;
  };
};

export const JsPlane = () => {
  const { nodes, materials } = useGLTF('/models/js_plane.glb') as GLTFResult;
  return (
    <group
      dispose={null}
      scale={0.3}
      position={[0, -1.5, 0]}
      rotation={[0, 1.1, 0]}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.mat_3220964}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload('/models/js_plane.glb');
