/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk.glb --types 
Author: draakon_4d (https://sketchfab.com/draakon_4d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-desk-98c5bd86d7bb4ca98dbc26dabb5e7196
Title: Computer Desk
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_14: THREE.Mesh;
  };
  materials: {
    comp_desk_c: THREE.MeshStandardMaterial;
    comp_desk: THREE.MeshStandardMaterial;
    comp_desk_b: THREE.MeshStandardMaterial;
    comp_desk_a: THREE.MeshStandardMaterial;
    comp_desk_remote: THREE.MeshStandardMaterial;
    comp_desk_2remote: THREE.MeshStandardMaterial;
    comp_desk_1remote: THREE.MeshStandardMaterial;
    comp_desk_button: THREE.MeshStandardMaterial;
    comp_desk_top: THREE.MeshStandardMaterial;
  };
};

export const Desk = () => {
  const { nodes, materials } = useGLTF('/models/desk.glb') as GLTFResult;
  return (
    <group
      dispose={null}
      scale={2}
      position={[0, -1.47, 1.4]}
      rotation={[0, Math.PI, 0]}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.comp_desk_c}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.comp_desk}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.comp_desk_b}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.comp_desk_a}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.comp_desk_remote}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.comp_desk_2remote}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.comp_desk_1remote}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.comp_desk_button}
        />
      </group>
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.comp_desk_top}
      />
    </group>
  );
};

useGLTF.preload('/models/desk.glb');
